### ISSUE TITLE
Add plugin badges

### ISSUE THREAD

**Issue by radeva** [NativeScript/marketplace-feedback#109]
- Add platforms support info for verified plugins
- Android versions
- iOS versions
- TS typings
- License
- Popularity
- Supported NativeScript versions
- CI
- Demo

**Comment by lini** [comment]
Stage one for badges to include: 
- Android versions (static) - plugin package.json should contain android platform
- iOS versions (static) - plugin package.json should contain ios platform
- NativeScript current and previous version (static) - plugin package.json file look for tns-* platform module dependency version OR look in nativescript platforms for runtimes version. **Facebook** (not published yet)
- CI (UX use Travis CI icon) - static test if plugin repo has .travis.yml file. Also check Travis API to see if integration is enabled.  **Mapbox** (no recent builds to check status)
- Demo - check repo for plugin and look for demo/demo-angular/demo-ng/demo-vue/examples folder. Alternatively, check for the name of the plugin appearing in a package.json file under "dependencies" in the repo. 
- Popularity (e.g. level per stars and downloads) (based on static analyze) - use npms popularity data and stars count. Decide what percent of plugins will become popular - e.g. top 1% of all plugins. 
- TS Typings – static from package.json - **Ripple** ("typings:" instead of "typings")
- License - icon showing what license is used by the plugin 

Pro ui data comes from ?

**Comment by lini** [comment]
AC:
1. ~~Verified badge is removed from plugin icons. Deprecated plugins should remain the same. - not executed!~~
1. There should be 9 badge icons on the plugin list page and in the plugin details. Tooltips on badge icons. - rating and current NS version may miss
1. "Recently Verified" plugins list is replaced with "Recently Added" plugins (4 plugins). Recently added means added to the Marketplace database, not created in NPM.
1. Verify that badges correspond to the list in the above comment. Note that wireframes might show more badges than the above list.
1. All badges should show correct plugin information only.
1. Marketplace loading speed should not be severely affected by the badges changes. Simulate slow 3G network (Chrome Dev Tools network tab).
1. Sync should only synchronize plugins that were updated from the previous sync.
