### ISSUE TITLE
Verified Plugins

### ISSUE THREAD

**Issue by david-quadpro** [NativeScript/marketplace-feedback#110]
Hi,

Now that NativeScript supports core, Angular and Vue, should the verified plugin criteria be amended to include support for Vue?

Currently, the 3rd criteria states that plugins should support all the technologies that NativeScript officially support. It that refers to angular and non-angular. As a suggestion, should this be amended to include Vue as the now third technology that NativeScript supports?

I am not sure how much work this places on the plugin developers since I have not used Vue yet but reading the criteria it seemed to make sense to include Vue too.

Happy to make the wording changes and submit a PR if there is agreements that Vue support is to be added as a requirement for Verified Plugin status.

Thanks,

David

**Comment by radeva** [comment]
Hi @david-quadpro ,

Thanks for approaching! Vue support is currently a community effort which for sure is good to be visible in a way in the Marketplace. Some time ago we realized that the term "verified" is understood in many different ways, that's why we're working in a direction to drop it and replace it with more visible representation of the plugin's qualities in the form of specific icons / badges. Having this in mind, it would be quite easy to add a badge for Vue support and Vue demo available in the plugin's repo. Having this in mind, we don't plan to do any changes to the Verified plugin criteria since soon it will be replaced. But we encourage every plugin author to add a Vue demo in the plugin's repo!

I hope this brings some light to the topic. Let me know if I can be of any further help!

Cheers,
Vesi

**Comment by david-quadpro** [comment]
Hi Vesi (@radeva )

Thanks for the information. That makes a lot of sense and I look forward to the new more descriptive badges.
