### ISSUE TITLE
Plugin `nativescript-shadowed-label` not showing

### ISSUE THREAD

**Issue by tralves** [NativeScript/marketplace-feedback#158]
Hello!

I created this plugin `nativescript-shadowed-label` and published it to npm (https://www.npmjs.com/package/nativescript-shadowed-label) but it is not being listed in the market. Am I missing something?

I used the plugin seed, everything according to the docs, I think...

**Comment by elena-p** [comment]
Hi @tralves,

Plugins are usually shown in the NativeScript market place within 24 hours of their publish to npm. However, there seems to be an issue with the information returned for your plugin from - http://registry.npmjs.org/-/v1/search?text=nativescript-shadowed-label. Could you try uploading again or [submitting an issue](https://npm.community/) in order to track what could have caused it.

**Comment by tralves** [comment]
Thank you for looking into it. I created the issue [here](https://npm.community/t/api-returning-wrong-data-in-from-http-registry-npmjs-org-v1-search-text-nativescript-shadowed-label/7010).

I guess all we can do now is wait, I guess...

**Comment by elena-p** [comment]
Hi @tralves,

It seems that the data returned from npmjs registry is now OK and the plugin is shown in the [{N} Marketplace](https://market.nativescript.org/plugins/nativescript-shadowed-label).

**Comment by tralves** [comment]
Cool! I didn't get a response from npm, but I am glad it works now. Thanks!
