### ISSUE TITLE
Wrong webpack issues from Travis CI

### ISSUE THREAD

**Issue by jdnichollsc** [NativeScript/marketplace-feedback#160]
> Namespace 'android' has no exported member 'content'.

Guys, I'm getting this report from Travis => https://travis-ci.com/proyecto26/nativescript-inappbrowser/jobs/198457052

But I'm not sure because I'm already using the last configuration of your NativeScript plugin seed as you can see from the repo here => https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/references.d.ts

Any help is really appreciated 👍

**Comment by elena-p** [comment]
Hi @jdnichollsc,

Your travis build is failing because there is no `npm i` called before calling `tsc` and platform declarations are not found in node-modules. You could include `npm i` at the beginning of either `tsc` or `build` scripts in your plugin's [package.json file](https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/package.json#L18). 

We are currently working on improving the NativeScript plugin seed and we will review the workflow and travis configurations in order to ensure that there are no such failures.

**Comment by jdnichollsc** [comment]
Thanks @elena-p, It works like a charm from `tsc` script 👍

**Comment by jdnichollsc** [comment]
@elena-p do you know how to fix the issue with the Android emulator from `Travis` too? https://travis-ci.org/proyecto26/nativescript-inappbrowser/jobs/529916601
